# Streamlit Application Inputs and Outputs

---

## 📂 Streamlit App Sample Inputs & Results (External Storage)

Due to GitHub file size limitations, large output files generated by the Streamlit application—such as:
- Annotated ultrasound video frames
- Processed result videos
- Sample inference outputs
- Visual analysis results

are hosted externally on Google Drive.

🔗 **Click here to access Streamlit App Sample Results**  
👉 [Google Drive – Streamlit App Outputs](https://drive.google.com/drive/folders/1S_IMCquXNZreDPKCVJvQ9M82xqgITTh5?usp=sharing)

---

This document explains the inputs accepted by the Streamlit web application and the outputs generated after analysis.

---

## Application Overview
- Web Framework: **Streamlit**
- Model Used: **YOLOv8-S (Instance Segmentation)**
- Deployment: Streamlit Cloud (Public)

---

## User Inputs

### 1. Patient Details
- Patient Name (optional)
- Patient Age (numeric)

### 2. Ultrasound Video Upload
- Supported Formats:
  - MP4
  - MOV
  - AVI
  - MPEG4
- Maximum file size:
  - 200 MB per video
- Processing Rate:
  - ~1 frame per second (FPS)

---

## Processing Pipeline
1. Video upload and validation
2. Frame extraction
3. Preprocessing for ultrasound enhancement
4. Model inference on each frame
5. Follicle detection and segmentation
6. Size estimation per follicle
7. Maturity classification

---

## Output Results

### 1. Visual Outputs
- Annotated video frames with:
  - Segmentation masks
  - Follicle boundaries
  - Size annotations
- Real-time processing status updates

### 2. Quantitative Outputs
- Total follicles detected
- Number of **mature follicles (≥ 18 mm)**
- Number of **immature follicles (< 18 mm)**
- Morphology-based indices

---

## Interpretation Notes
- Model confidence scores indicate prediction certainty
- Clinical interpretation should consider ultrasound quality
- Outputs are intended for **decision support**, not standalone diagnosis

---

## Limitations
- Processing time depends on video length
- Performance may vary with poor-quality ultrasound recordings

---

## Future Enhancements
- Downloadable CSV report
- Session-wise result history
- Improved confidence calibration
